spring:
  boot:
    admin:
      client:
        url: http://localhost:4444/

  datasource:
    url: jdbc:mysql://localhost:3306/Spring
    username: root
    password: parshu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
