spring:
  boot:
    admin:
      client:
        url: http://localhost:4444/
  datasource:
    username: root
    password: parshu
    url: jdbc:mysql://localhost:3306/spring

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials 
